karpenter:
  serviceAccount:
    create: false
  nodeSelector:
    node_group: karpenter
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "karpenter"
      effect: "NoSchedule"
  aws:
